<?php defined('SYSPATH') or die('No direct script access.');

class Controller_Welcome extends Site
{
    public $template = 'template';

    public function before()
    {
        $this->show_strategy = true;
        parent::before(); // TODO: Change the autogenerated stub
    }

    public function after()
    {
        parent::after();
    }


    public function action_index()
    {
        $this->page->title(__('Ең ұшқыр ақпарат құралы! Жаңа стильдегі медиа'));
        $this->page->meta(__('Жаңа медиа. Ең ұшқыр электронды ақпарат құралы. Қазақ тіліндегі мақалалар, журналистік зерттеулер, сұхбаттар, видеолар. Жаңа стиль. Ең үздік журналистер командасы.'), 'description');
        $data = Model_News::get_category_news();
        $view = View::factory('main_page')
            ->set('index', 0)
            ->bind('data', $data);
        $this->page->content($view);
    }

    public function action_doit()
    {
        $model = ORM::factory('News');
        $title = $this->request->post('title');
        if ($title) {
            $model->where('title', 'LIKE', DB::expr("'%{$title}%'"));
        } else {
            $model->where('id', '=', 66613666);
        }
        $view = View::factory('news/temp')
            ->bind('model', $model);
        $this->page->content($view);

    }

    public function action_testme()
    {
        $this->render = false;
        $query = "call megatest('ru');";
        $res = DB::query(Database::SELECT, $query)->execute();
        foreach ($res as $r) {
            var_dump($r);
        };
    }


} // End Welcome
